<?php


namespace App\Controller;


use App\database\EntityManager;
use App\database\manager\MetierManager;
use App\database\PreparedQuery;
use App\database\Query;
use App\Entity\AbonnementEntreprise;
use App\Entity\Langue;
use App\Entity\SituationFamille;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class UtilsController
 * @package App\Controller
 * @Route("/utils")
 */
final class UtilsController extends AbstractController
{
    /**
     * All TypeContrat
     */
    private const TYPES_CONTRAT = ['CDD', 'CDI', 'Saisonnier', 'Job d\'appoint'];
    /**
     * All Metier
     */
    private const METIERS = [
        'Agriculture' => [
            'Agriculteur',
            'Agronome',
            'Berger',
            'Conseiller de gestion agricole',
            'Chargé d\'affaires agricoles',
            'Conducteur de machines agricoles',
            'Fermier',
            'Conchyliculteur',
            'Horticulteur',
            'Juriste agricole',
            'Cueilleur',
            'Cultivateur',
            'Paysan',
            'Maraîcher',
            'Employé',
            'Entreposeur',
            'Exécutant',
            'Ingénieur d\'étude',
            'Viticulteur',
            'Vigneron',
            'Métayer',
            'Ouvrier',
            'Responsable',
            'Technicien',
            'Responsable d\'élevage',
        ],
        'Agro-alimentaire/Alimentation' => [
            'Boucher',
            'Boulanger',
            'Brasseur malteur',
            'Agent de distribution',
            'Agent de manutention',
            'Céréalier',
            'Charcutier',
            'Conseiller de programme',
            'Conseiller viticole',
            'Crémier',
            'Crêpier',
            'Directeur de supermarché',
            'Frigoriste',
            'Laitier',
            'Meunier',
            'Pizzaïolo',
            'Poissonnier',
            'Primeur',
            'Écailler',
            'Mareyeur',
            'Directeur',
            'Employé',
            'Entreposeur',
            'Exécutant',
            'Fabricant',
            'Garde-manger',
            'Ingénieur d\'étude',
            'Ingénieur de fabrication',
            'Ouvrier',
            'Technicien',
            'Œnologue',
            'Rôtisseur',
            'Saunier',
            'Testeur culinaire',
            'Maître ouvrier',
            'Manager de l\'innovation',
            'Opérateur',
            'Préparateur méthodes',
            'Responsable',
            'Testeur',
        ],
        'Animaux' => [
            'Assistant vétérinaire',
            'Auxiliaire de santé animale (vétérinaire)',
            'Animalier en laboratoire',
            'Aquaculteur',
            'Chargé de recherche animalier',
            'Cadre d\'écurie',
            'Dompteur',
            'Dresseur',
            'Éducateur canin',
            'Éleveur',
            'Enseignant animateur équestre',
            'Fauconnier',
            'Maître chien',
            'Ostéopathe animalier',
            'Pet sitter',
            'Maréchal-ferrant',
            'Palefrenier',
            'Directeur',
            'Employé',
            'Exécutant',
            'Herpétologue',
            'Ingénieur d\'étude',
            'Soigneur animalier',
            'Toiletteur',
            'Vendeur en animalerie',
            'Vétérinaire',
            'Zoologiste',
            'Zoologue',
            'Zoothérapeute',
            'Lad-driver',
            'Lad-jockey',
            'Loueur d\'équidés',
            'Ouvrier',
            'Responsable',
            'Technicien',
        ],
        'Architecture/Aménagement intérieur' => [
            'Aménageur d\'espace intérieur',
            'Animateur 2D',
            'Animateur 3D',
            'BIM Manager',
            'Architecte',
            'Architecte d\'intérieur',
            'Architecte du patrimoine',
            'Architecte paysagiste',
            'Chargé du développement',
            'Concepteur',
            'Chef décorateur',
            'Cuisiniste',
            'Designer',
            'Designer mobilier',
            'Dessinateur',
            'Designer produit',
            'Décorateur',
            'Décorateur d\'intérieur',
            'Conseiller de programme',
            'Développeur de produits',
            'Designer manager',
            'Développeur d\'enseigne',
            'Directeur',
            'Employé',
            'Exécutant',
            'Ingénieur d\'étude',
            'Ergonome',
            'Modélisateur',
            'Métreur',
            'Manager de l\'innovation',
            'Urbaniste',
            'Product manager',
            'Product owner',
            'Responsable',
            'Technicien',
            'Testeur',
        ],
        'Artisanat/Métier d\'art' => [
            'Acheteur d\'art',
            'Agent artistique',
            'Apiculteur',
            'Apprêteur',
            'Bijoutier',
            'Ardoisier',
            'Armurier',
            'Archetier',
            'Argenteur',
            'Artificier',
            'Artisan fromager',
            'Artiste peintre',
            'Chausseur',
            'Âtrier',
            'Batteur d\'or',
            'Chocolatier-confiseur',
            'Chocolatier',
            'Boutonnier',
            'Briquetier',
            'Brodeur',
            'Cirier',
            'Créateur de parfum',
            'Décorateur-étalagiste',
            'Dentellier',
            'Designer céramique',
            'Dinandier',
            'Employé',
            'Encadreur',
            'Entreposeur',
            'Facteur d\'instruments',
            'Bronzier',
            'Calligraphe',
            'Campaniste',
            'Chaudronnier',
            'Canneur-rempailleur',
            'Céramiste',
            'Chaîniste',
            'Chapelier',
            'Charron',
            'Chaumier',
            'Cordonnier',
            'Costumier',
            'Corsetier',
            'Coutelier',
            'Créateur',
            'Créateur de mode',
            'Ébéniste',
            'Ferronnier d\'art',
            'Coffreur-boiseur',
            'Confiseur',
            'Ciseleur',
            'Décorateur en résine',
            'Diamantaire',
            'Exécutant',
            'Fabricant',
            'Féron',
            'Feutrier',
            'Fondeur',
            'Fontainier',
            'Formier',
            'Forgeron',
            'Fromager',
            'Glacier',
            'Graveur sur pierre',
            'Joaillier',
            'Ferrailleur',
            'Graveur',
            'Horloger',
            'Ferronnier',
            'Maître tailleur',
            'Maître verrier',
            'Maître-ouvrier d\'art',
            'Maquettiste',
            'Maquettiste automobile',
            'Menuisier',
            'Menuisier en sièges',
            'Métallier',
            'Mosaïste',
            'Orfèvre',
            'Pâtissier',
            'Graveur de poinçons',
            'Ivoirier',
            'Laqueur',
            'Ouvrier',
            'Parfumeur',
            'Perruquier',
            'Piqueur',
            'Plisseur',
            'Raffineur',
            'Technicien',
            'Peintre en décor',
            'Peintre en lettres',
            'Peintre solier',
            'Peintre sur mobilier',
            'Peintre',
            'Escaliéteur',
            'Enlumineur',
            'Émailleur sur lave',
            'Émailleur sur métal',
            'Doreur',
            'Doreur sur cuir',
            'Doreur sur tranche',
            'Dominotier',
            'Éventailliste',
            'Fresquiste',
            'Gemmologue',
            'Glypticien',
            'Guillocheur',
            'Imagier au pochoir',
            'Maroquinier',
            'Rappeur',
            'Testeur',
            'Marqueteur de pailles',
            'Marqueteur de pierres dures',
            'Mégissier',
            'Modiste',
            'Nacrier',
            'Ostréiculteur',
            'Parqueteur',
            'Passementier',
            'Pipier',
            'Gantier',
            'Fourreur',
            'Lapidaire',
            'Maître de chai',
            'Marbrier',
            'Marqueteur',
            'Mytiliculteur',
            'Luthier',
            'Restaurateur',
            'Restaurateur d\'art',
            'Sculpteur',
            'Sculpteur sur bois',
            'Sculpteur sur métal',
            'Sculpteur sur pierre',
            'Sellier',
            'Sellier bourrelier',
            'Sellier d\'ameublement',
            'Sellier maroquinier',
            'Serrurier',
            'Serrurier métallier',
            'Shaper',
            'Soudeur',
            'Souffleur de verre',
            'Staffeur ornemaniste',
            'Stratifieur',
            'Tailleur',
            'Tailleur de pierre',
            'Tanneur',
            'Tapissier',
            'Tapissier d\'ameublement',
            'Tapissier garnisseur',
            'Tatoueur',
            'Taillandier',
            'Taxidermiste',
            'Tisserand',
            'Tôlier',
            'Tonnelier',
            'Tuilier',
            'Vernisseur',
            'Zingueur',
            'Plasticien',
            'Plumassier',
            'Porcelainier',
            'Potier',
            'Potier d\'étain',
            'Quincaillier',
            'Ramoneur',
            'Relieur',
            'Relieur-doreur',
            'Sertisseur',
            'Product manager',
            'Product owner',
            'Responsable',
            'Solier-moquettiste',
            'Tabletier',
            'Voilier-sellier',
            'Tourneur sur bois',
            'Tourneur sur métal',
            'Vitrailliste',
            'Vannier',
            'Verrier',
        ],
        'Audiovisuel/Numérique/Multimédia' => [
            'Accordeur (instrument)',
            'Acousticien',
            'Animateur radio',
            'Agent de distribution',
            'Animateur de télévision',
            'Character designer',
            'Chargé de programmation',
            'Chargé du développement',
            'Caméraman',
            'Cadreur',
            'Chanteur',
            'Chargé de production vidéo',
            'Compositeur',
            'Compositeur de musique',
            'Conseiller en image',
            'Critique d\'art',
            'Critique de cinéma',
            'Designer graphique',
            'Conseiller de programme',
            'Directeur',
            'Employé',
            'Étalonneur numérique',
            'Exécutant',
            'Infographe',
            'Ingénieur d\'étude',
            'Designer graphiste',
            'Développeur multimédia',
            'Designer de réalité virtuelle',
            'Graphiste',
            'Illustrateur',
            'Illustrateur 3D',
            'Infographiste',
            'Ingénieur du son',
            'Journaliste radio',
            'Designer sonore',
            'E-sportif',
            'Game designer',
            'Musicien',
            'Présentateur radio',
            'Présentateur télé',
            'Photographe',
            'Programmeur',
            'Programmeur de jeux vidéo',
            'Layout artist',
            'Habilleur',
            'Harpiste',
            'Immersive designer',
            'Influenceur',
            'Ingénieur télépilote',
            'Lead game designer',
            'Technicien des effets spéciaux',
            'Technicien vidéo',
            'Testeur de jeux vidéo',
            'Scénariste',
            'Level designer',
            'Mixeur',
            'Monteur incorporateur',
            'Pilote de drone',
            'Pro gamer',
            'Photocompositeur',
            'Professionnels du dessin animé',
            'Projectionniste',
            'Réalisateur',
            'Réalisateur de cinéma',
            'Réalisateur de plateau',
            'Réalisateur de radio',
            'Réalisateur VR',
            'Réalisateur de téléfilms',
            'Manager de l\'innovation',
            'Media planner',
            'Modérateur',
            'Monteur',
            'Opérateur',
            'Perchman',
            'Producteur',
            'Sound designer',
            'Télépilote audiovisuel',
            'UX designer',
            'UI designer',
            'Product manager',
            'Product owner',
            'Tools programmer',
            'Responsable',
            'Story-boarder',
            'Streamer',
            'Technical artist',
            'Technicien d\'antenne',
            'Testeur',
            'Violoniste',
            'Youtuber',
        ],
        'Banque/Finance/Assurance' => [
            'Agent d\'assurance',
            'Analyste crédit',
            'Analyste financier',
            'Chargé de conformité',
            'Agent général d\'assurances',
            'Banquier',
            'Auditeur financier',
            'Actuaire',
            'Agent de change',
            'Analyste',
            'Animateur économique',
            'Auditeur externe',
            'Auditeur interne',
            'Chargé d\'affaire',
            'Chargé du développement',
            'Conseiller financier',
            'Conseiller fiscal',
            'Contrôleur financier',
            'Courtier',
            'Courtier en assurances',
            'Conseiller',
            'Conseiller en assurances',
            'Consolideur',
            'Convoyeur de fonds',
            'Credit manager',
            'Data scientist',
            'Directeur',
            'Employé',
            'Exécutant',
            'Courtier en bourse',
            'Économe',
            'Économiste',
            'Expert comptable',
            'Employé d\'assurance',
            'Employé de banque',
            'Expert assurance',
            'Expert-comptable',
            'Conseiller de programme',
            'Ingénieur financier',
            'Juriste dans les assurances',
            'Directeur financier',
            'Éco-conseiller',
            'Mandataire liquidateur',
            'Fiscaliste',
            'Gérant de portefeuille',
            'Gestionnaire d\'actifs',
            'Trader',
            'Risk manager',
            'Souscripteur',
            'Rédacteur de contrats',
            'Responsable',
            'Trésorier',
            'Technicien du patrimoine',
            'Technicien de paie',
            'Conseiller en économie sociale',
        ],
        'Bâtiment/Travaux public' => [
            'Carreleur',
            'Agent de distribution',
            'Agent de manutention',
            'Assistant chef de chantier',
            'Charpentier',
            'Charpentier bois',
            'Chef de chantier',
            'Chef de travaux',
            'Conducteur d\'engin de chantier',
            'Chauffagiste',
            'Chargé d\'affaire',
            'Conducteur de travaux',
            'Contrôleur de travaux',
            'Couvreur',
            'Échafaudeur',
            'Éclairagiste',
            'Économiste de la construction',
            'Électricien',
            'Étancheur',
            'Façadier',
            'Conseiller de programme',
            'Contremaître',
            'Directeur',
            'Employé',
            'Exécutant',
            'Planificateur OPC',
            'Démolisseur',
            'Grutier',
            'Ingénieur électricien',
            'Maçon',
            'Dalleur',
            'Électricien d\'équipement',
            'Géomètre',
            'Géomètre expert',
            'Géomètre topographe',
            'Ingénieur du BTP',
            'Monteur électricien',
            'Monteur en isolation thermique',
            'Monteur-câbleur',
            'Paveur-dalleur',
            'Peintre en bâtiment',
            'Plaquiste',
            'Plâtrier',
            'Plombier/Chauffagiste',
            'Faïencier',
            'Entreposeur',
            'Ingénieur d\'étude',
            'Ingénieur de fabrication',
            'Maître ouvrier',
            'Manage de l\'innovation',
            'Ouvrier',
            'Terrassier',
            'Photogrammètre',
            'Vitrier',
            'Tireur de cable',
            'Responsable',
            'Technicien',
        ],
        'Biologie/Chimie/Recherche' => [
            'Biochimiste',
            'Biologiste',
            'Biologiste médical',
            'Agronome',
            'Biomathématicien',
            'Aromaticien',
            'Aromaticien parfumeur',
            'Chef de laboratoire',
            'Chimiste',
            'Chercheur',
            'Biophysicien',
            'Biotechnologue',
            'Chargé du développement',
            'Exobiologiste',
            'Ethnologue',
            'Géochimiste',
            'Géographe',
            'Géologue',
            'Ingénieur chimiste',
            'Ingénieur de recherche',
            'Directeur',
            'Employé',
            'Exécutant',
            'Logisticien nucléaire',
            'Ingénieur biomécanique',
            'Hydrobiologiste',
            'Hydrogéologue',
            'Océanographe',
            'Océanologue',
            'Éthologue',
            'Laborantin',
            'Formulateur',
            'Glaciologue',
            'Goûteur d\'eau',
            'Ingénieur d\'étude',
            'Ingénieur de fabrication',
            'Statisticien',
            'Technicien biologiste',
            'Technicien de laboratoire',
            'Qualiticien',
            'Manager de l\'innovation',
            'Opérateur',
            'Préparateur',
            'Responsable conseil brevets',
            'Responsable',
            'Volcanologue',
            'Ingénieur civil',
            'Ingénieur en aéronautique',
            'Technicien',
            'Testeur',
        ],
        'Commerce (Vendeur/Commercial)' => [
			'Acheteur',
			'Acheteur dans la mode',
			'Acheteur industriel',
			'Agent de location',
			'Agent immobilier',
			'Agent commercial du transport',
			'Agent de vente',
			'Animateur commerciale',
			'Animateur des ventes',
			'Assistant commercial',
			'Attaché commercial',
			'Attaché commercial sédentaire',
			'Administrateur de ventes',
			'Assureur',
			'Caissier',
			'Chef de caisse',
			'Commerçant',
			'Commerçant franchisé',
			'Bid Manager',
			'Commercial',
			'Chef de promotion',
			'Chef de secteur',
			'Commercial télécoms',
			'Conseiller',
			'Conseiller en vente directe',
			'Conseiller professionnel',
			'Consultant',
			'Consultant e-business',
			'Consultant e-commerce',
			'Credit manager',
			'Directeur',
			'Disquaire',
			'Employé',
			'Étalagiste',
			'Buraliste',
			'Conseiller de vente luxe',
			'Cambiste',
			'Category manager',
			'Caviste',
			'Chargé du développement',
			'Chef de comptoir',
			'Chef de marché',
			'Chef de projet digital',
			'Chef de rayon',
			'Chef des ventes',
			'Directeur commercial',
			'Directeur d\'agence',
			'Directeur de boutique',
			'Grossiste',
			'Ingénieur commercial',
			'Inspecteur commercial',
			'Ingénieur technico-commercial',
			'Directeur des ventes',
			'Directeur régional des ventes',
			'Démonstrateur',
			'Démonstrateur de marque',
			'Détaillant',
			'Exécutant',
			'Fleuriste',
			'Fournisseur',
			'Gainier',
			'Gestionnaire de contrats',
			'Growth Hacker',
			'Infopreneur',
			'Ingénieur d\'affaires',
			'Kiosquier',
			'Manager de la marque',
			'Directeur des achats',
			'Épicier',
			'Droguiste',
			'Santonnier',
			'Technico-commercial',
			'Vendeur',
			'Vendeur automobile',
			'Vendeur en magasin',
			'Vendeur moto',
			'Manager dans le luxe',
			'Marchand de journaux',
			'Responsable de vente',
			'Manager de l\'innovation',
			'Responsable e-commerce',
			'Merchandiser',
			'Skiman',
			'VRP',
			'Vendeur export',
			'Vendeur technique',
			'Product manager',
			'Product owner',
			'Responsable d\'affaire',
			'Responsable d\'agence',
			'Responsable',
			'Télévendeur',
			'Visual merchandiser',
			'Yield manager',
        ],
        'Communication/Information' => [
			'Assistant de communication',
			'Assistant marketing',
			'Analyste marketing',
			'Agent de presse',
			'Chargé de communication',
			'Chargé de packaging',
			'Aide-documentaliste',
			'Architecte d\'information',
			'Chef de projet marketing',
			'Auditeur',
			'Communication',
			'Business developer',
			'Chargé du développement',
			'Chef de l\'information',
			'Chef de publicité',
			'Chef de rubrique',
			'Consultant marketing',
			'Designer packaging',
			'Chef de pub',
			'Consultant',
			'Correcteur',
			'Correspondant local',
			'Critique gastronomique',
			'Data journaliste',
			'Directeur',
			'Employé',
			'Exécutant',
			'Directeur de communication',
			'Directeur marketing',
			'Démographe',
			'Iconographe',
			'Influenceur',
			'Journaliste d\'entreprise',
			'Kiosquier',
			'Localier',
			'Marketeur',
			'Responsable communication',
			'Responsable éditorial',
			'Responsable éditorial web',
			'Manager de l\'innovation',
			'Manager de la marque',
			'Responsable marketing',
			'Responsable marketing digital',
			'Responsable marketing sportif',
			'Media planner',
			'Roughman',
			'Modérateur',
			'Planner stratégique',
			'Postier',
			'Product manager',
			'Product owner',
			'Reporter en agence',
			'Responsable d\'antenne',
			'Responsable de l\'information',
			'Responsable',
			'Responsable emailing',
			'Trader média',
			'Traffic manager',
			'Technicien',
			'Veilleur stratégique',
			'Visual merchandiser',
			'Youtubeur',
        ],
        'Culture/Spectacle' => [
			'Bruiteur',
			'Acteur',
			'Acrobate',
			'Agent de manutention',
			'Animateur de spectacle',
			'Animateur de tourisme local',
			'Animateur socio-culturel',
			'Attaché culturel',
			'Accessoiriste',
			'Adjoint animation',
			'Animateur',
			'Artiste de cirque',
			'Assistant opérateur',
			'Assistant réalisateur',
			'Assistant son',
			'Chef d\'orchestre',
			'Auteur',
			'Comédien',
			'Chorégraphe',
			'Clown',
			'Directeur',
			'Employé',
			'Exécutant',
			'Conseiller culturel',
			'Chef de chœur',
			'Cascadeur',
			'Caster',
			'Concept artist',
			'Directeur artistique',
			'Funambule',
			'Imitateur',
			'Décorateur-scénographe',
			'Humoriste',
			'Figurant',
			'Marionnettiste',
			'Metteur en scène',
			'Dialoguiste',
			'Ensemblier',
			'Entreposeur',
			'Exécutant',
			'Habilleur',
			'Scénographe',
			'Scripte',
			'Interprète',
			'Jongleur',
			'Technicien du spectacle',
			'Trapéziste',
			'Magicien',
			'Prestidigitateur',
			'Régisseur',
			'Manager de l\'innovation',
			'Mime',
			'Ouvrier',
			'Responsable',
			'Technicien',
			'Testeur',
        ],
        'Défense/Sécurité/Secours' => [
			'Agent de police',
			'Agent de sécurité',
			'Adjoint de sécurité',
			'Agent de distribution',
			'Attaché de police',
			'ASVP',
			'Capitaine de sapeur-pompier',
			'Administrateur civil',
			'Administrateur territorial',
			'Agent de manutention',
			'Agent secret',
			'Analyste SOC',
			'Commissaire de police',
			'Commissaire des armées',
			'Conseiller à la sécurité',
			'Capitaine',
			'Contrôleur des douanes',
			'Contrôleur qualité',
			'Douanier',
			'Gendarme',
			'Contrôleur aérien',
			'Data protection officer',
			'Directeur',
			'Employé',
			'Exécutant',
			'Espion',
			'Expert en sécurité',
			'Expert incendies et risques',
			'Gardien',
			'Gendarme adjoint volontaire',
			'Lieutenant de police',
			'Lieutenant de sapeur-pompier',
			'Lieutenant pénitentiaire',
			'Déclarant en douane',
			'Démineur',
			'Garde du corps',
			'Garde du littoral',
			'Militaire',
			'Officier de marine',
			'Officier de police',
			'Pilote de char',
			'Pilote de chasse',
			'Pilote de ligne',
			'Pompier',
			'Policier',
			'Diplomate',
			'Entreposeur',
			'Gardien de la paix',
			'Lieutenant de pont',
			'Officier',
			'Sapeur pompier',
			'Sécurité civile',
			'Shérif',
			'Soldat',
			'Surveillant pénitentiaire',
			'Technicien alarme intrusion',
			'Télépilote sapeur-pompier',
			'Veilleur de nuit',
			'Maître nageur sauveteur',
			'Major de sapeur-pompier',
			'Personnel de surveillance',
			'Responsable de la sécurité',
			'Responsable expatriation',
			'Responsable',
			'Technicien',
        ],
        'Droit' => [
			'Analyste juridique',
			'Avocat',
			'Avocat à la cour de cassation',
			'Avocat au Conseil d\'État',
			'Avocat d\'affaires',
			'Avocat du droit des personnes',
			'Avocat pénaliste',
			'Assistant de sénateur',
			'Assistant juridique',
			'Assistant de justice',
			'Administrateur judiciaire',
			'Clerc d\'huissier',
			'Clerc de notaire',
			'Avoué',
			'Commissaire priseur',
			'Contrôleur du travail',
			'Député',
			'Expert judiciaire',
			'Commissaire aux comptes',
			'Directeur',
			'Employé',
			'Exécutant',
			'Juge',
			'Juge aux affaires familiales',
			'Juge d\'instance',
			'Juge d\'instruction',
			'Juge des enfants',
			'Juge des tutelles',
			'Juriste',
			'Juriste social',
			'Magistrat',
			'Greffier',
			'Huissier',
			'Huissier de justice',
			'Juriste en cybersécurité',
			'Mandataire judiciaire',
			'Notaire',
			'Juriste d\'entreprise',
			'Secrétaire-assistant juridique',
			'Substitut du procureur',
			'Substitut général',
			'Inspecteur',
			'Inspecteur d\'académie',
			'Inspecteur de la DGCCRF',
			'Inspecteur du travail',
			'Inspecteur en génie sanitaire',
			'Inspecteur-vérificateur',
			'Médiateur culturel',
			'Médiateur pénal',
			'Médiateur social',
			'Ministre',
			'Officier d’état civil',
			'Premier ministre',
			'Procureur',
			'Procureur de la République',
			'Sénateur',
			'Politicien',
			'Préfet',
			'Questeur',
			'Secrétaire d\'État',
			'Responsable conseil brevets',
			'Responsable',
			'Administrateur du senat',
			'Attaché de préfecture',
			'Conseiller municipal',
			'Conseiller national',
			'Conseiller régional',
			'Conseiller général',
			'Homme politique',
        ],
        'Edition/Littérature/Imprimerie' => [
			'Biographe',
			'Bibliothécaire',
			'Bibliothécaire adjoint',
			'Agent de distribution',
			'Assistant blibliothécaire',
			'Agent de routage',
			'Chargé du développement',
			'Chef de fabrication',
			'Critique littéraire',
			'Dessinateur de bande dessinées',
			'Dessinateur de presse',
			'Écrivain',
			'Écrivain public',
			'Éditeur',
			'Chromiste',
			'Claviste',
			'Conseiller de programme',
			'Conservateur de bibliothèque',
			'Conteur',
			'Journaliste',
			'Copiste',
			'Correcteur',
			'Directeur',
			'Éditeur-directeur éditorial',
			'Employé',
			'Exécutant',
			'Fabricant',
			'Libraire',
			'Imprimeur',
			'Documentaliste',
			'Documentaliste TV',
			'Journaliste web',
			'Journaliste reporter d\'images',
			'Journaliste pour une émission',
			'Grand reporter',
			'Entreposeur',
			'Linotypiste',
			'Ingénieur de fabrication',
			'Rubricard',
			'Lecteur-correcteur',
			'Lithographe',
			'Narrateur',
			'Pigiste',
			'Rédacteur',
			'Rédacteur de documentation',
			'Rédacteur de presse',
			'Rédacteur-reporter',
			'Manager de l\'innovation',
			'Margeur',
			'Massicotier',
			'Ouvrier',
			'Rédacteur en chef',
			'Relecteur',
			'Reporter-photographe',
			'Reporter',
			'Responsable d\'édition',
			'Mangaka',
			'Secrétaire d\'édition',
			'Sérigraphe',
			'Packager éditorial',
			'Pressier',
			'Product manager',
			'Product owner',
			'Responsable',
			'Stenotypiste',
			'Typographe',
			'Technicien',
			'Testeur',
        ],
        'Enseignement/Formation' => [
			'Assistant d\'éducation',
			'Chargé de formation',
			'ATSEM',
			'Coach professionnel',
			'Coach de vie',
			'Coach de couple',
			'Coach parental',
			'Coach',
			'Coach deco',
			'Conseiller conjugal',
			'Conseiller d\'éducation',
			'Conseiller d\'orientation',
			'Campus-manager',
			'Éducateur',
			'Éducateur de jeunes enfants',
			'Enseignant',
			'Enseignant-chercheur',
			'Éducateur spécialisé',
			'Formateur',
			'Moniteur d\'auto-école',
			'Diacre',
			'Directeur',
			'Employé',
			'Exécutant',
			'Moniteur de plongée',
			'Moniteur de ski',
			'Moniteur de sport',
			'Moniteur de voile',
			'Moniteur éducateur',
			'Professeur des écoles',
			'Professeur de lycée',
			'Professeur',
			'Professeur d\'université',
			'Professeur de collège',
			'Professeur d\'art dramatique',
			'Professeur d\'arts plastiques',
			'Professeur d\'EPS',
			'Professeur de danse',
			'Professeur de musique',
			'Professeur de sport',
			'Designer d\'interaction',
			'Intervenant en milieu scolaire',
			'Linguiste',
			'Surveillant',
			'Instituteur',
			'Love coach',
			'Maître de conférence',
			'Manager eSport',
			'Orienteur professionnel',
			'Proviseur',
			'Responsable formation',
			'Outplacer',
			'Responsable',
        ],
        'Esthétique/Coiffure/Soins' => [
			'Coiffeur',
			'Barbier',
			'Conseiller en beauté',
			'Consultant bien-être',
			'Designer de mode',
			'Designer textile',
			'Esthéticienne',
			'Journaliste de mode',
			'Couturier',
			'Photographe de mode',
			'Directeur',
			'Employé',
			'Exécutant',
			'Maquilleur',
			'Mannequin',
			'Styliste',
			'Styliste modéliste',
			'Styliste ongulaire',
			'Vendeur en prêt-à-porter',
			'Modéliste',
			'Patronnier gradeur',
			'Retoucheur',
			'Spa praticien',
			'Premier d\'atelier',
			'Socio-esthéticien',
			'Teinturier',
			'Responsable',
			'Spa manager',
			'Testeur',
        ],
        'Environnement/Nature/Nettoyage' => [
			'Agent technique forestier',
			'Animateur nature',
			'Agent d\'entretien',
			'Agent de distribution',
			'Botaniste',
			'Bûcheron',
			'Balayeur',
			'Cartographe',
			'Éboueur',
			'Élagueur',
			'Expert naturaliste',
			'Conseiller en environnement',
			'Garde forestier',
			'Garde-moniteur du parc national',
			'Garde-pêche',
			'Guide de haute montagne',
			'Ingénieur environnement',
			'Ingénieur forestier',
			'Jardinier',
			'Jardinier paysagiste',
			'Cordiste',
			'Développeur économique',
			'Développeur rural',
			'Directeur',
			'Écotoxicologue',
			'Employé',
			'Exécutant',
			'Explorateur',
			'Directeur environnement',
			'Laveur de vitre',
			'Paysagiste',
			'Entreposeur',
			'Fossoyeur',
			'Garde-champêtre',
			'Garde-chasse',
			'Glaciologue',
			'Ingénieur analyste de l\'air',
			'Ingénieur d\'étude',
			'Ingénieur écologue',
			'Sylviculteur',
			'Technicien forestier',
			'Ingénieur écologue',
			'Ingénieur en dépollution',
			'Ingénieur en génie thermique',
			'Ingénieur fluides',
			'Naturaliste',
			'Pépiniériste',
			'Responsable géographique',
			'Manager de l\'innovation',
			'Ouvrier',
			'Pêcheur',
			'Responsable',
			'Technicien',
        ],
        'Gestion/RH' => [
			'Assistant comptable',
			'Assistant de gestion PME-PMI',
			'Assistant RH',
			'Assistant chef de projet',
			'Adjoint de direction',
			'Administrateur territorial',
			'Assistant de direction',
			'Assistant en recrutement',
			'Auditeur social',
			'Chargé d\'études personnels',
			'Comptabilité',
			'Comptable',
			'Comptable immobilier',
			'Chargé de recrutement',
			'Chasseur de tête',
			'Conseiller en gestion des RH',
			'Chef de projet e-recrutement',
			'Contrôleur de gestion',
			'DRH',
			'Chef de service',
			'Conseiller d\'insertion',
			'Consultant en recrutement',
			'Directeur',
			'Employé',
			'Exécutant',
			'Directeur RH',
			'Gestion de patrimoine',
			'Gestionnaire de paie',
			'Gérant de patrimoine',
			'Gestionnaire de carrière',
			'Gestionnaire de services',
			'Lobbyiste',
			'Office manager',
			'Responsable développement RH',
			'Maître ouvrier',
			'Manager des ressources',
			'Ressources humaines',
			'Président-directeur général',
			'Responsable',
			'Superviseur',
			'Test manager',
        ],
        'Histoire/Histoire de l\'art' => [
			'Archéologue',
			'Antiquaire',
			'Animateur du patrimoine',
			'Archiviste',
			'Administrateur territorial',
			'Conservateur de musée',
			'Conservateur des archives',
			'Conservateur du patrimoine',
			'Expert d\'art',
			'Égyptologue',
			'Commissaire d\'exposition',
			'Historien',
			'Muséographe',
			'Paléontologue',
			'Directeur',
			'Employé',
			'Exécutant',
			'Galeriste',
			'Régisseur d\'œuvre d\'art',
			'Responsable',
        ],
        'Hôtellerie/Restauration/Tourisme' => [
			'Barman',
			'Chef cuisinier',
			'Chef de partie',
			'Chef de rang',
			'Commis de cuisine',
			'Commis',
			'Concierge d\'hôtel',
			'Concierge de grand hôtel',
			'Chef de cuisine',
			'Chef réceptionniste',
			'Cuisinier',
			'Directeur d\'hôtel',
			'Directeur d\'un hôtel de luxe',
			'Directeur de la restauration',
			'Garçon de café',
			'Équipier en restaurant rapide',
			'Femme de chambre',
			'Gérant d\'hôtel',
			'Hôtelier',
			'Hôtesse d\'accueil',
			'Directeur',
			'Employé',
			'Exécutant',
			'Maître d\'hôtel',
			'Plongeur',
			'Réceptionniste',
			'Réceptionniste d\'hôtel',
			'Serveur',
			'Valet de chambre',
			'Manager dans la restauration',
			'Entremétier',
			'Forfaitiste',
			'Gouvernante',
			'Guest relation manager',
			'Lingère',
			'Saucier',
			'Sommelier',
			'Traiteur',
			'Voiturier',
			'Limonadier',
			'Plagiste',
			'Portier',
			'Responsable',
			'Technicien',
        ],
        'Humanitaire' => [
			'Chef de mission humanitaire',
			'Logisticien humanitaire',
			'Directeur',
			'Employé',
			'Entreposeur',
			'Exécutant',
			'Fundraiser',
			'Responsable',
			'Technicien',
        ],
        'Immobilier/Urbanisme' => [
        	'Administrateur de biens',
			'Administrateur territorial',
			'Agent de location',
			'Aménageur foncier',
			'Aménageur lotisseur',
			'Architecte fonctionnel SI',
			'Asset manager',
			'Chargé du développement',
			'Diagnostiqueur immobilier',
			'Expert immobilier',
			'Conseiller',
			'Conseiller de programme',
			'Consultant',
			'Juriste d\'immobilier',
			'Juriste en droit immobilier',
			'Gestionnaire immobilier',
			'Mandataire immobilier',
			'Négociateur immobilier',
			'Directeur',
			'Employé',
			'Exécutant',
			'Facility manager ',
			'Gestionnaire de copropriété',
			'Gestionnaire locatif',
			'Promoteur immobilier',
			'Prospecteur foncier',
			'Responsable de projet immoblier',
			'Programmiste',
			'Responsable',
			'Technicien',
        ],
        'Informatique/Electronique' => [
			'Analyste Web',
			'Architecte web',
			'Bio-informaticien',
			'Analyste',
			'Administrateur réseaux',
			'Administrateur système',
			'Analyste fonctionnel',
			'Analyste programmeur',
			'Architecte Big Data',
			'Architecte de réseaux',
			'Chef de produit Web',
			'Attaché analyste-informaticien',
			'Bionaute',
			'Concepteur de jeux vidéos',
			'Concepteur numérique',
			'Concepteur web',
			'Chargé du développement',
			'Chef de projet informatique',
			'Développeur',
			'Développeur base de données',
			'Chief Digital Officer',
			'Community manager',
			'Consultant en informatique',
			'Consultant IT',
			'Consultant progiciel',
			'Consultant SAAS',
			'Consultant web analytic',
			'Content manager',
			'Correspondant Informatique',
			'Digital Evangelist',
			'Directeur',
			'E-consultant interne',
			'Employé',
			'Exécutant',
			'Développeur informatique',
			'Développeur web',
			'Domoticien',
			'Graphiste web',
			'Informaticien',
			'Ingénieur informaticien',
			'Cyberdocumentaliste',
			'Data analyst',
			'Ergonome Web',
			'Ergonome du logiciel',
			'Ingénieur Big data',
			'Intégrateur web',
			'Expert d\'infrastructure',
			'Flash designer',
			'Flasheur',
			'Growth Hacker',
			'Hacker éthique',
			'Immersive designer',
			'Matte painter',
			'Infographe',
			'Infopreneur',
			'Ingénieur CFAO',
			'Ingénieur cloud computing',
			'Ingénieur cogniticien',
			'Ingénieur d\'étude',
			'Ingénieur de fabrication',
			'Ingénieur électronicien',
			'Ingénieur électrotechnicien',
			'Intégrateur',
			'Intégrateur d\'exploitation',
			'Manager de l\'innovation',
			'Responsable',
			'Webdesigner',
			'Webdeveloper',
			'Webmarketeur',
			'Responsable e-commerce',
			'Roboticien',
			'Modérateur',
			'Motion designer',
			'Netsurfer',
			'Opérateur',
			'Photograveur',
			'Technicien d\'infrastructures',
			'Product manager',
			'Product owner',
			'Scrum master',
			'Webmaster',
			'Webplanner',
			'Web analyste',
			'Technologue',
			'Technicien',
			'Testeur',
        ],
        'Industrie/Usine' => [
			'Agent de distribution',
			'Agent de manutention',
			'Ajusteur-monteur',
			'Assistant de production',
			'Calorifugeur',
			'Cartonnier',
			'Chargé de production',
			'Chef de fabrication',
			'Chef de produit industriel',
			'Chef de produits',
			'Designer industriel',
			'Dessinateur industriel',
			'Droit industriel',
			'Chef opérateur',
			'Conseiller de programme',
			'Coupeur',
			'Directeur',
			'Employé',
			'Entreposeur',
			'Exécutant',
			'Ingénieur d\'étude',
			'Ingénieur de fabrication',
			'Technicien plasturgiste',
			'Ingénieur génie industriel',
			'Ingénieur textile',
			'Modeleur',
			'Mouleur',
			'Opérateur de production',
			'Maître ouvrier',
			'Responsable de fabrication',
			'Manager de l\'innovation',
			'Opérateur',
			'Ouvrier',
			'Pilote de production',
			'Poêlier',
			'Polisseur',
			'Préparateur méthodes',
			'Technicien d\'exploitation',
			'Tourneur-fraiseur',
			'Product manager',
			'Product owner',
			'Responsable de conditionnement',
			'Responsable de production',
			'Responsable',
			'Wappeur',
			'Tuyauteur',
			'Technicien qualité',
			'Technicien',
			'Testeur',
        ],
        'Mécanique/Maintenance' => [
			'Ascensoriste',
			'Agent de maintenance',
			'Carrossier',
			'Agent de distribution',
			'Carrossier réparateur',
			'Carrossier-peintre',
			'Agent de manutention',
			'Aiguilleur',
			'Chef mécanicien',
			'Automaticien',
			'Contrôleur technique',
			'Dépanneur-remorqueur',
			'Dépanneur',
			'Électronicien automobile',
			'Électrotechnicien',
			'Expert d’automobile',
			'Garagiste',
			'Ingénieur en mécanique',
			'Mécanicien',
			'Mécanicien automobile',
			'Directeur',
			'Employé',
			'Entreposeur',
			'Exécutant',
			'Mécanicien aéronautique',
			'Mécanicien d\'aéronefs',
			'Mécanicien moteur',
			'Mécanicien moto',
			'Mécanicien réparateur',
			'Machiniste',
			'Hydraulicien',
			'Ingénieur d\'affaires',
			'Ingénieur d\'étude',
			'Technicien',
			'Technicien ascensoriste',
			'Technicien de maintenance',
			'Technicien réseau',
			'Responsable de maintenance',
			'Maître ouvrier',
			'Manager de l\'innovation',
			'Mécanicien robinetier',
			'Opérateur',
			'Ouvrier',
			'Responsable',
			'Technicien d\'essai',
			'Technicien',
			'Testeur',
        ],
        'Maths/Sciences/Physique' => [
			'Anthropologue',
			'Astronome',
			'Astrophysicien',
			'Astronaute',
			'Géophysicien',
			'Ingénieur',
			'Ingénieur calcul',
			'Géomaticien',
			'Mathématicien',
			'Météorologiste',
			'Météorologue',
			'Physicien',
			'Physicien médical',
			'Cosmonaute',
			'Cryptologue',
			'Directeur',
			'Employé',
			'Exécutant',
			'Ingénieur cogniticien',
			'Sismologue',
			'Responsable',
			'Traducteur',
			'Traducteur-interprète',
			'Traducteur spécialisé',
			'Traducteur-réviseur',
			'Spationaute',
			'Veilleur technologique',
			'Testeur',
        ],
        'Santé' => [
			'Aide médico-psychologique',
			'Aide-soignant',
			'Ambulancier',
			'Agent de distribution',
			'Anesthésiste',
			'Aromathérapeute',
			'Brancardier',
			'Assistant médical',
			'Audioprothésiste',
			'Assistant dentaire',
			'Acuponcteur',
			'Cancérologue',
			'Cardiologue',
			'Agent de service hospitalier',
			'Analyste',
			'Chirurgien',
			'Chirurgien dentiste',
			'Chiropracteur',
			'Chirurgien esthétique',
			'Chirurgien orthopédiste',
			'Comportementaliste',
			'Convoyeur de l\'air',
			'Coordonnateur SPS',
			'Directeur',
			'Employé',
			'Exécutant',
			'Dentiste',
			'Diététicien',
			'Délégué médical',
			'Délégué pharmaceutique',
			'Directeur d\'hôpital',
			'Dermatologue',
			'Gynécologue',
			'Hydrothérapeute',
			'Infirmier',
			'Infirmier-anesthésiste',
			'Infirmier de bloc opératoire',
			'Infirmier en pratique avancée',
			'Infirmier scolaire',
			'Ingénieur hospitalier',
			'Inhalothérapeute',
			'Kinésithérapeute',
			'Kinésithérapeute du sport',
			'Lunetier',
			'Masseur',
			'Masseur kinésithérapeute',
			'Graphologue',
			'Préparateur',
			'Médecin',
			'Médecin légiste',
			'Naturopathe',
			'Neurologue',
			'Nutritionniste',
			'Ophtalmologue',
			'Opticien',
			'Opticien lunetier',
			'Optométriste',
			'Orthodontiste',
			'Orthopédiste-orthésiste',
			'Orthophoniste',
			'Orthoprothésiste',
			'Orthoptiste',
			'Ostéopathe',
			'Paramédicaux',
			'Parapharmacien',
			'Pédiatre',
			'Pédicure / podologue',
			'Pédopsychiatre',
			'Pharmacien',
			'Physiothérapeute',
			'Podo-orthésiste',
			'Préparateur en pharmacie',
			'Prothésiste',
			'Prothésiste dentaire',
			'Psychanalyste',
			'Psychiatre',
			'Psychologue',
			'Psychomotricien',
			'Psychosociologue',
			'Psychothérapeute',
			'Radiologue',
			'Réflexologue',
			'Relaxologue',
			'Sage-femme',
			'Secrétaire médicale',
			'Sexologue',
			'Sociologue',
			'Sophrologue',
			'Urgentiste',
			'Urologue',
			'Visiteur médical',
			'Hygiéniste dentaire',
			'Ingénieur biomédical',
			'Ingénieur nutritionniste',
			'Directeur médical',
			'Ergothérapeute',
			'Équicien',
			'Docteur',
			'Étiopathe',
			'Néphrologue',
			'Herboriste',
			'Magnétiseur',
			'Maïeuticien',
			'Secrétaire-assistant médical',
			'Technicien en analyse médicale',
			'Musicothérapeute',
			'Puéricultrice',
			'Manipulateur d\'électroradiologie',
			'Psychologue clinicien',
			'Psychologue du travail',
			'Psychologue en libéral',
			'Psychologue scolaire',
			'Rééducateur',
			'Opérateur',
			'Manipulateur radio',
			'Thanatopracteur',
			'Product manager',
			'Product owner',
			'Responsable',
			'Technicien',
			'Testeur',
        ],
        'Secrétariat/Accueil' => [
			'Adjoint administratif',
			'Agent d\'accueil',
			'Billettiste',
			'Chargé d\'accueil',
			'Chargé d\'assistance',
			'Chargé de clientèle',
			'Chargé de recouvrement',
			'Employé administratif',
			'Conseiller',
			'Déontologue',
			'Directeur',
			'Employé',
			'Exécutant',
			'Guichetier',
			'Hotliner',
			'Secrétaire',
			'Secrétaire administratif',
			'Standardiste',
			'Secrétaire de rédaction',
			'Responsable',
			'Secrétaire de documentation',
			'Téléphoniste',
			'Télévendeur',
        ],
        'Service à la personne/Social' => [
			'Assistante sociale',
			'Auxiliaire de puériculture / de crèche',
			'Auxiliaire de vie',
			'Chargé de mission handicap',
			'Animateur de club de vacances',
			'Animateur petite enfance',
			'Assistante maternelle',
			'Assistant familial',
			'Assistant de service social',
			'AES',
			'Agent funéraire',
			'Butler',
			'Chauffeur de direction',
			'Chauffeur de maître',
			'Coursier',
			'Conseiller familial',
			'Coordinateur de crèches',
			'Délégué à la tutelle',
			'Coordinateur social',
			'Majordome',
			'Détective',
			'Détective privé',
			'Directeur',
			'Employé',
			'Exécutant',
			'Gardien d\'immeuble',
			'Habilleur',
			'Nourrice',
			'Responsable relations sociales',
			'Téléassistant',
			'Téléconseiller',
			'Responsable',
			'Travailleur social',
			'Accompagnateur de personnes à mobilité réduite',
			'Accompagnant d’élève en situation de handicap',
        ],
        'Sport/Animation' => [
			'Arbitre',
			'Athlète',
			'Agent de joueur sportif',
			'Chef de produit sportif',
			'Coach de fitness',
			'Coach eSport',
			'Chef de projet eSport',
			'Chef de projet événementiel',
			'Danseur',
			'Éducateur sportif',
			'Entraîneur',
			'Médecin du sport',
			'Nutritionniste sportif',
			'Journaliste sportif',
			'Juriste du sport',
			'Directeur des sports',
			'Nageur',
			'Pilote',
			'Préparateur physique',
			'Croupier',
			'Directeur',
			'Employé',
			'Exécutant',
			'Jockey',
			'Sportif de haut niveau',
			'Sportif professionnel',
			'Organisateur d\'événements',
			'Organisateur e-sport',
			'Patineur',
			'Personal Trainer',
			'Responsable d\'animation',
			'Responsable',
			'Trader sportif',
			'Wakeboarder',
			'Wedding planner',
        ],
        'Tourisme' => [
        	'Agent de distribution',
			'Agent de sûreté',
			'Agent de voyages',
			'Chef de car',
			'Chef de produits voyages',
			'Chef de projet consultant',
			'Conseiller',
			'Guide touristique',
			'Consultant en tourisme',
			'Directeur marketing touristique',
			'Directeur',
			'Employé',
			'Exécutant',
			'Forfaitiste',
			'Guide Interprète',
			'Guide-accompagnateur',
			'Guide-conférencier',
			'Hôtesse de l\'air',
			'Perchman',
			'Responsable',
			'Steward',
			'gv',
        ],
        'Transport/Logistique' => [
			'Animateur logistique',
			'Agent de transit',
			'Agent logisticien',
			'Agent de distribution',
			'Agent de manutention',
			'Affréteur',
			'Approvisionneur',
			'Camionneur',
			'Chauffeur',
			'Chauffeur de bus',
			'Chauffeur de Grande Remise',
			'Chauffeur de Petite Remise',
			'Chauffeur routier (PL)',
			'Chauffeur de taxi',
			'Chauffeur-livreur',
			'Armateur',
			'Capitaine de navire',
			'Cariste',
			'Chef de gare',
			'Commandant de bord',
			'Directeur',
			'Employé',
			'Entreposeur',
			'Exécutant',
			'Ouvrier',
			'Batelier',
			'Conducteur',
			'Conducteur de bus',
			'Conducteur de train',
			'Conducteur de tramway',
			'Conducteur routier',
			'Chargeur',
			'Contrôleur',
			'Chef d\'escale',
			'Chef d\'exploitation',
			'Dameur',
			'Agent de distribution',
			'Agent de manutention',
			'Facteur',
			'Chef de train funiculaire',
			'Livreur',
			'Logisticien',
			'Déménageur',
			'Éclusier',
			'Magasinier',
			'Forfaitiste',
			'Merchandiser',
			'Planificateur OPC',
			'Technicien',
			'Marin de la marine marchande',
			'Marinier',
			'Navigateur aérien',
			'Pilote d\'avion',
			'Pilote d\'exploitation',
			'Pilote d\'hélicoptère',
			'Préparateur de commande',
			'Docker',
			'Gestionnaire de stock',
			'Hôtesse de l\'air',
			'Manutentionnaire cariste',
			'Routier',
			'Skipper',
			'Transporteur',
			'Marin',
			'Préparateur de vol',
			'Péagiste',
			'Responsable de logistique',
			'Manager de la supply chain',
			'Responsable logistique',
			'Responsable d\'entrepôt',
			'Responsable d\'exploitation',
			'Responsable',
			'Steward',
			'Second capitaine',
			'Wagonnier',
			'Wattman',
			'Aiguilleur du ciel',
			'Aiguilleur du rail',
			'Aviateur',
        ]
    ];
    /**
     * All Langue
     */
    private const LANGUES = ['Albanais', 'Allemand', 'Anglais', 'Arabe', 'Arménien', 'Basque', 'Bengali', 'Birman',
        'Bulgare', 'Catalan', 'Chinois', 'Cingalais', 'Coréen', 'Corse', 'Croate', 'Danois', 'Espagnol', 'Espéranto',
        'Estonien', 'Finnois', 'Français', 'Gaélique', 'Galicien', 'Gallois', 'Géorgien', 'Grec', 'Hébreu', 'Hindi',
        'Indonésien', 'Italien', 'Japonais', 'Javanais', 'Khmer', 'Latin', 'Letton', 'Lituanien', 'Malaisien',
        'Néerlandais', 'Népalais', 'Norvégien', 'Polonais', 'Portugais', 'Roumain', 'Russe', 'Serbe', 'Slovaque',
        'Slovène', 'Suédois', 'Tchèque', 'Turc', 'Ukrainien', 'Vietnamien'];
    /**
     * All SituationFamille
     */
    private const SITUATIONS_FAMILLE = ['Célibataire', 'En couple'];
    /**
     * All AbonnementEntreprise
     */
    private const ABONNEMENTS_ENTREPRISE = [
        ['nom' => '1 Annonce', 'description' => '1 seule annonce', 'montant' => 20],
        ['nom' => '5 Annonces', 'description' => 'Jusqu\'à 5 annonces', 'montant' => 16],
        ['nom' => '20 Annonces', 'description' => 'Jusqu\'à 20 annonces', 'montant' => 14],
        ['nom' => '30 Annonces', 'description' => 'Jusqu\'à 30 annonces', 'montant' => 12],
        ['nom' => '40 Annonces', 'description' => 'Jusqu\'à 40 annonces', 'montant' => 10],
        ['nom' => 'Abonnement', 'description' => 'Autant d\'annonces que vous voulez', 'montant' => 10],
    ];

    /**
     * @Route("/fill")
     * @param EntityManagerInterface $em
     * @return JsonResponse
     */
    public function fillBdd(EntityManagerInterface $em): JsonResponse
    {
        $alreadyFilled = true;

        // Fill TypeContrat
        foreach (self::TYPES_CONTRAT as $typeContrat) {
            if ((new PreparedQuery('MATCH (t:' . EntityManager::TYPE_CONTRAT . ' {nom:$nom}) RETURN t'))
                    ->setString('nom', $typeContrat)
                    ->run()
                    ->getOneOrNullResult() == null) { // If not exist
                $alreadyFilled = false;
                (new PreparedQuery('CREATE (:' . EntityManager::TYPE_CONTRAT . ' {nom:$nom})'))
                    ->setString('nom', $typeContrat)
                    ->run(); // Create
            }
        }

        // Fill Metier
        foreach (self::METIERS as $secteurActivite => $metiers) {
            if ((new PreparedQuery('MATCH (s:' . EntityManager::SECTEUR_ACTIVITE . ' {nom:$nom}) RETURN s'))
                    ->setString('nom', $secteurActivite)
                    ->run()
                    ->getOneOrNullResult() == null) { // If not exist
                $alreadyFilled = false;
                (new PreparedQuery('CREATE (:' . EntityManager::SECTEUR_ACTIVITE . ' {nom:$nom})'))
                    ->setString('nom', $secteurActivite)
                    ->run(); // Create
            }

            foreach ($metiers as $metier) {
                if ((new PreparedQuery('MATCH (m:' . EntityManager::METIER . ' {nom:$nom}) RETURN m'))
                        ->setString('nom', $secteurActivite)
                        ->run()
                        ->getOneOrNullResult() == null) { // If not exist
                    $alreadyFilled = false;
                    (new MetierManager())->create($metier, $secteurActivite);
                }
            }
        }

        // Fill Langue
        foreach (self::LANGUES as $langue) {
            if ($em->getRepository(Langue::class)->findOneBy(['nom' => $langue]) == null) {
                $alreadyFilled = false;
                $l = (new Langue())
                    ->setNom($langue);
                $em->persist($l);
            }
        }
        $em->flush();

        // Fill SituationFamille
        foreach (self::SITUATIONS_FAMILLE as $situationFamille) {
            if ($em->getRepository(SituationFamille::class)->findOneBy(['nom' => $situationFamille]) == null) {
                $alreadyFilled = false;
                $s = (new SituationFamille())
                    ->setNom($situationFamille);
                $em->persist($s);
            }
        }
        $em->flush();

        // Fill AbonnementEntreprise
        foreach (self::ABONNEMENTS_ENTREPRISE as $abonnementEntreprise) {
            if ($em->getRepository(AbonnementEntreprise::class)->findOneBy(['nom' => $abonnementEntreprise['nom']]) == null) {
                $alreadyFilled = false;
                $a = (new AbonnementEntreprise())
                    ->setNom($abonnementEntreprise['nom'])
                    ->setDescription($abonnementEntreprise['description'])
                    ->setMontant($abonnementEntreprise['montant']);
                $em->persist($a);
            }
        }
        $em->flush();

        if ($alreadyFilled)
            return $this->json(['result' => 'already_filled']);
        else
            return $this->json(['result' => 'filled']);
    }
}
